version: "3"
services:
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    image: codesentry-web
    container_name: codesentry-web
    working_dir: /var/www/codesentry
    volumes:
      - ./web:/var/www/codesentry
    ports:
      - "8089:8089"
    networks:
      - codesentry-network

  api:
    build:
      dockerfile: api.dockerfile
      context: .
    image: codesentry-api
    container_name: codesentry-api
    working_dir: /var/www
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - ./api:/var/www
    networks:
      - codesentry-network

  mongo:
    image: mongo:4.4.8-focal
    container_name: codesentry-mongo
    ports:
      - 27017:27017
    volumes:
      - "./mongo/:/data/db"
    networks:
      - codesentry-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: codesentry

  mongo-test:
    image: mongo:4.4.8-focal
    container_name: codesentry-mongo-test
    ports:
      - 27018:27017
    volumes:
      - "./mongo/test:/data/db"
    networks:
      - codesentry-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: codesentry

networks:
  codesentry-network:
    driver: bridge
